### ISSUE TITLE
Rename operators

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#218]
- [x] `airflow.gcp.hooks.base`
- [x] `airflow.gcp.hooks.bigquery`
- [x] `airflow.gcp.hooks.dataproc`
- [x] `airflow.gcp.hooks.gcs`
- [x] `airflow.gcp.hooks.sql`
- [x] `airflow.gcp.operators.bigquery` https://github.com/PolideaInternal/airflow/issues/406 
- [x] `airflow.gcp.operators.bigquery_to_gcs` https://github.com/PolideaInternal/airflow/issues/406
- [x] `airflow.gcp.operators.dataproc` https://github.com/PolideaInternal/airflow/issues/407
- [x] `airflow.gcp.operators.gcs` https://github.com/PolideaInternal/airflow/issues/409
- [x] `airflow.gcp.operators.gcs_to_bq` https://github.com/PolideaInternal/airflow/issues/409
- [x] `airflow.gcp.operators.gcs_to_gcs` https://github.com/PolideaInternal/airflow/issues/409 
- [x] `airflow.gcp.operators.local_to_gcs` https://github.com/PolideaInternal/airflow/issues/410
- [x] `airflow.gcp.operators.sql` https://github.com/PolideaInternal/airflow/issues/411
- [x] `airflow.gcp.sensors.bigquery` https://github.com/PolideaInternal/airflow/issues/412
- [x] `airflow.gcp.sensors.gcs` https://github.com/PolideaInternal/airflow/issues/413
- [x] `airflow.operators.adls_to_gcs` https://github.com/PolideaInternal/airflow/issues/414
- [x] `airflow.operators.cassandra_to_gcs` https://github.com/PolideaInternal/airflow/issues/415
- [x] `airflow.operators.gcs_to_s3` https://github.com/PolideaInternal/airflow/issues/424
- [x] `airflow.operators.mssql_to_gcs` https://github.com/PolideaInternal/airflow/issues/425
- [x] `airflow.operators.mysql_to_gcs` https://github.com/PolideaInternal/airflow/issues/426
- [x] `airflow.operators.postgres_to_gcs` https://github.com/PolideaInternal/airflow/issues/427
- [x] `airflow.operators.sql_to_gcs` https://github.com/PolideaInternal/airflow/issues/428

**Comment by nuclearpinguin** [comment]
Any update on that @michalslowikowski00 ?

**Comment by michalslowikowski00** [comment]
@nuclearpinguin only this `airflow.gcp.hooks.gcs` left.
